### PR TITLE
Added tqdm to csv_to_database.py

### PR DESCRIPTION
**Pull request by Olajumoke01**
To let users know the timeline of the loading of data into the database as this took a long time.

### CODE REVIEW

**Review by cptanalatriste — APPROVED** [review]
Looks good to me! @Iain-S , I remember talking about using progress bars with other SSG commands. Do we have issues for that?

**Comment by cptanalatriste** [comment]
@Olajumoke01 , a post-merge question: was `tqdm` already within your virtual environment, or you need to install it?

**Comment by Olajumoke01** [comment]
Hi Carlos, yes I had to install tqdm first.

**Comment by cptanalatriste** [comment]
@Olajumoke01 , we manage our dependencies using `poetry` so they're automatically added to `pyproject.toml` (without the need for the manual install). Can you please add `tqdm` as an extra dependency using `poetry add tqdm --group=extras
`. It should add the necessary lines to `pyproject.toml` file.

**Pull request merged**
